<a href="https://colab.research.google.com/github/dienyaaa/python-homework/blob/ML/%D0%94%D0%97_%D0%9A%D0%B8%D1%81%D0%BB%D0%B8%D1%86%D0%B8%D0%BD_%D0%9C%D0%9E_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# План:
1. Python
2. Numpy
3. Regexp

# Python

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)

In [ ]:
"ada ".capitalize()+"lovelace ".capitalize()+"was considered the world's first computer programmer."

"Ada Lovelace was considered the world's first computer programmer."

2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

In [ ]:
print("       Whitespaces  left and   right    ".rstrip())
print("       Whitespaces  left and   right    ".lstrip())
print("       Whitespaces  left and   right    ".strip())

       Whitespaces  left and   right
Whitespaces  left and   right    
Whitespaces  left and   right


3. Найти первое вхождение в строку подстроки (☆☆☆)

In [ ]:
s1="But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
s2="you"

s1.find(s2)

7

4. Разбить строку по разделителю (☆☆☆)

In [ ]:
s1="Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"

s1_list = s1.split('#')

5. Полученный массив строк склеить через пробел (★☆☆)

In [ ]:
' '.join(s1_list)

'Holy cow, Rick! I didn’t know hanging out with you was making me smarter!'

6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

In [ ]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}

s = ["{} (age {}) is a {}".format(value[0], value[1], value[2]) for key, value in personal_data.items()]
print(*s, sep = '\n')

Ann (age 29) is a Artist
Leo (age 54) is a Programmer
Tiffany (age 43) is a Shop Assistant


7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

In [ ]:
year = int(input())
print('YES') if year % 400 == 0 or (year % 4 == 0 and year % 100 != 0) else print('NO')

2012
YES


8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [ ]:
words = ['Not', 'my', 'cup', 'of', 'tea']

{key: hash(key) for key in words}

{'Not': 140536044390658224,
 'my': -6752552943153195900,
 'cup': -5384680843089499244,
 'of': 7914510372478635695,
 'tea': 5007609760667864435}

9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [ ]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']

del dogs[1]
dogs.remove('labrador retriever')
dogs

['border collie']

10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [ ]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']

print(list(i.upper() for i in dogs[2:5]))

['AUSTRALIAN', 'CATTLE', 'DOG']


11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [ ]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }

s, ls = "", []
for key, value in pets.items():
  s += key.capitalize() + " is a {}. It's owner is {}. It's {vac} vaccinated.".format(
      value['kind'], value['owner'].capitalize(), vac = "" if value['vaccinated'] else "not")
  ls.append(s)
  s = ""
print(*ls, sep = '\n')

Willie is a dog. It's owner is Eric. It's  vaccinated.
Walter is a cockroach. It's owner is Eric. It's not vaccinated.
Peso is a dog. It's owner is Chloe. It's  vaccinated.


12. Проверить является ли множество подмножеством другого множества  (★☆☆)

In [ ]:
a=set([2, 5, 6])
b=set([2, 4, 8, 3, 5, 6])

a.issubset(b)

True

13. Объединить несколько множеств (★☆☆)

In [ ]:
a=set([10, 35, 6, 5])
b=set([2, 4, 8, 3, 5, 6, 35])
c=set([4, 5, 35])

a.union(b).union(c)

{2, 3, 4, 5, 6, 8, 10, 35}

14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)


In [ ]:
a.intersection(b).intersection(c)

{5, 35}

15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. (★★☆)

In [ ]:
a=set([1, 2, 3, 4, 5])
b=set([3, 4, 5, 6, 7])

a.symmetric_difference(b)

{1, 2, 6, 7}

16. Предположим, есть файл с данными клиентов. В качестве простого примера возьмем txt-файл(нужно создать файл с предложенным/другим содержанием самостоятельно) следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

In [ ]:
import json

credit_file = open('/content/sample_data/credit_sample.txt', 'r')
header = credit_file.readline().strip()
header_list = header.split(',')
print(header_list)

lines = [line.strip().split(',') for line in credit_file if line.strip()]
dictionary = {"clients": {line[0]: (line[1], line[2], line[3]) for line in lines}}
print(dictionary)

unique_occ = set()
for key, value in dictionary['clients'].items():
  unique_occ.add(value[2].lower())

print(len(unique_occ))

credit_file.close()

with open('credit_data.json', 'w') as outfile:
  json.dump(dictionary, outfile, indent = 4)

['lastname', 'age', 'debt', 'occupation']
{'clients': {'Adrianov': ('25', '30000', 'artist'), 'Belkin': ('42', '4000', 'programmer'), 'Koltunov': ('32', '100', 'sportsman'), 'Loptev': ('25', '30000', 'artist'), 'Bobrov': ('42', '4000', 'programmer'), 'Karelin': ('32', '100', 'sportsman')}}
3


### os, sys, datetime

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

In [ ]:
import os

files = os.listdir('gifs')
print(files)
gifs = []
for file in files:
  if file.endswith('.gif'):
    gifs.append(file)
print(gifs)

['sample_640×426.gif', 'pnggrad8rgb.png', 'sample_1920×1280.gif', 'sample_1280×853.gif']
['sample_640×426.gif', 'sample_1920×1280.gif', 'sample_1280×853.gif']


18. Создать папку с названием temp и удалить её (★☆☆)

In [ ]:
if not os.path.exists(r'temp'):
  os.makedirs('temp')
os.rmdir('temp')

19. Вывести переменные среды (★☆☆)

In [ ]:
os.environ

environ{'NV_LIBCUBLAS_DEV_VERSION': '11.4.1.1043-1',
        'NV_CUDA_COMPAT_PACKAGE': 'cuda-compat-11-2',
        'NV_CUDNN_PACKAGE_DEV': 'libcudnn8-dev=8.1.1.33-1+cuda11.2',
        'LD_LIBRARY_PATH': '/usr/local/nvidia/lib:/usr/local/nvidia/lib64',
        'NV_LIBNCCL_DEV_PACKAGE': 'libnccl-dev=2.8.4-1+cuda11.2',
        'TCLLIBPATH': '/usr/share/tcltk/tcllib1.19',
        'CLOUDSDK_PYTHON': 'python3',
        'LANG': 'en_US.UTF-8',
        'NV_LIBNPP_DEV_PACKAGE': 'libnpp-dev-11-2=11.3.2.152-1',
        'HOSTNAME': '3c041815964f',
        'OLDPWD': '/',
        'CLOUDSDK_CONFIG': '/content/.config',
        'NV_LIBNPP_VERSION': '11.3.2.152-1',
        'NV_NVPROF_DEV_PACKAGE': 'cuda-nvprof-11-2=11.2.152-1',
        'NVIDIA_VISIBLE_DEVICES': 'all',
        'NV_NVPROF_VERSION': '11.2.152-1',
        'NV_LIBCUSPARSE_VERSION': '11.4.1.1152-1',
        'DATALAB_SETTINGS_OVERRIDES': '{"kernelManagerProxyPort":6000,"kernelManagerProxyHost":"172.28.0.3","jupyterArgs":["--ip=172.28.0.2"],"de

20. Как игнорировать warrnings?

In [ ]:
import sys

if not sys.warnoptions:
    import warnings
    warnings.simplefilter("ignore")

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [ ]:
from datetime import date, timedelta

print("Today is {}".format(date.today()))
print("Yesterday was {}".format(date.today() - timedelta(days = 1)))
print("Tomorrow is {}".format(date.today() + timedelta(days = 1)))

Today is 2022-10-26
Yesterday was 2022-10-25
Tomorrow is 2022-10-27


22. Вывести день недели сегодняшней даты (★☆☆)

In [ ]:
print(date.today().weekday())
print(date.today().strftime('%A'))

2
Wednesday


23. Получить список дат за предыдущую неделю (★★☆)

In [ ]:
print(*[date.today() - timedelta(days = i) for i in range(7,0,-1)])

2022-10-19 2022-10-20 2022-10-21 2022-10-22 2022-10-23 2022-10-24 2022-10-25


24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)

In [ ]:
from datetime import datetime

print(datetime.now().strftime('%d.%m.%Y %H:%M:%S'))

26.10.2022 13:01:59


25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [ ]:
print(date.today() - timedelta(weeks = 1))

2022-10-19


# Numpy

In [ ]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Как найти размер занимаемой памяти любым массивом (★☆☆)


In [ ]:
np.ones(100).itemsize

8

3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [ ]:
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

4. Создать вектор от 10 до 50 включительно (★☆☆)


In [ ]:
a = np.arange(10, 51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [ ]:
a[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)


In [ ]:
np.reshape(np.arange(9), (3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Найти индексы не нулевых элементов в numpy array [1,2,0,0,4,0] (★☆☆)

In [ ]:
a = np.array([1, 2, 0, 0, 4, 0])
print(*a.nonzero())

[0 1 4]


8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [ ]:
a = np.random.randint(10000, size = (10,10))
print(a)
print(a.min())
print(a.max())
print(np.mean(a))

[[6408 3596 2857 5922 3214 1267  481 9970 2289 3751]
 [3570 1008 8417 9582 3346 8387 5530  762 9773  365]
 [5512 4134  112 2885 9364 6050 4571 3834 4184 8642]
 [5301 3493 3290 1542 4173 2498 3601 4843 6040 8336]
 [  28   64 3114  978 8503 2830 6026 3166 7922 1932]
 [8522 3431 4334 8197 6300 1047 8258  942 4032 8403]
 [9851 1496 1263 7843 9724 5163 7386 7802 5542 5720]
 [2513 9441  356 7043 3614 9714 6237 8968 1916 4072]
 [3789 5922 4674 1520 3892 6419 2657  843 7726 4759]
 [7802 6639 5559 6700 1379 2994 7312 9401 5827 4448]]
28
9970
4868.55


9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

In [ ]:
np.indices((8,8)).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

10. Нормализовать рандомную матрицу 5x5 (★☆☆)


In [ ]:
a = np.random.randint(10000, size = (5,5))
print(a)
print(np.sum(a, axis = 1)[:, np.newaxis]) #сумма элементов в каждой строке не равна 1
print('\n')

normalized_a = a / np.linalg.norm(a, axis = 1, ord = 1)[:, np.newaxis]
print(normalized_a)
print(np.sum(normalized_a, axis = 1)[:, np.newaxis])

[[4754  839 3913 9519  314]
 [5313 9032 6409 3358 6809]
 [3627 5748 9993 2537 4332]
 [3889 7888  176 8799 5502]
 [7950 8786 6759  840 5085]]
[[19339]
 [30921]
 [26237]
 [26254]
 [29420]]


[[0.2458245  0.04338384 0.20233725 0.4922178  0.01623662]
 [0.17182497 0.29209922 0.20727014 0.10859933 0.22020633]
 [0.13823989 0.21907993 0.38087434 0.09669551 0.16511034]
 [0.14812981 0.30044946 0.00670374 0.33514893 0.20956807]
 [0.27022434 0.29864038 0.22974167 0.02855201 0.1728416 ]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


11. Найти общие элементы между двумя массивами


In [ ]:
x = np.random.randint(10, size = (3,3))
print(x, "\n")
y = np.random.randint(10, size = (3,3))
print(y, "\n")
print(np.intersect1d(x,y))

[[2 0 1]
 [8 7 8]
 [0 5 9]] 

[[3 8 9]
 [7 2 2]
 [7 2 2]] 

[2 7 8 9]


12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆)

In [ ]:
a = np.random.uniform(0, 10, 10)
print(a, '\n')

print(np.trunc(a))
print(np.round(a))
print(a // 1)
print(a - a % 1)
print(a.astype(int))

[3.82419583e+00 2.39235654e+00 6.66039280e+00 1.61430056e+00
 6.30680058e+00 2.97419237e+00 6.42333788e-01 1.86111852e+00
 9.24971482e+00 7.92438979e-03] 

[3. 2. 6. 1. 6. 2. 0. 1. 9. 0.]
[4. 2. 7. 2. 6. 3. 1. 2. 9. 0.]
[3. 2. 6. 1. 6. 2. 0. 1. 9. 0.]
[3. 2. 6. 1. 6. 2. 0. 1. 9. 0.]
[3 2 6 1 6 2 0 1 9 0]


13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

In [ ]:
sorted(np.random.randint(1000, size = 10))

[124, 159, 305, 344, 375, 539, 543, 596, 924, 953]

14. Проверить одинаковы ли два рандомных массива А и B (★★☆)


In [ ]:
a = np.array([[1,2,6], [5,5,8]])
b = np.array([[1,2,6], [5,5,8]])
np.array_equal(a, b)

True

15. Создать рандомный вектор размером 10 и максимальный элемент заменить на -1 (★★☆)


In [ ]:
a = np.random.randint(10000, size = 10)
print(a)

a[a.argmax()] = -1
print(a)

[3909 3955 1283 8833 2338  272 1572 6089 3685 4445]
[3909 3955 1283   -1 2338  272 1572 6089 3685 4445]


16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)


In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)

index = (np.abs(Z - v)).argmin()
print(Z[index])

97.29572023632376
97


17. Посчитать среднее для каждой строки матрицы (★★☆)

In [ ]:
a = np.random.randint(1000, size = (5,5))
print(a, '\n')
print(np.mean(a, axis = 1)[:, np.newaxis])

[[243 208 752 517  26]
 [644 408 824 677 532]
 [911 539 271 262 967]
 [128 835 512 795 829]
 [720 903 230 305 804]] 

[[349.2]
 [617. ]
 [590. ]
 [619.8]
 [592.4]]


18. Посчитать среднее со скользящим окном над массивом (★★★)


In [ ]:
def cumulative_mean(array, window):
  cumulative_arr = np.cumsum(array)
  cumulative_arr[window:] = cumulative_arr[window:] - cumulative_arr[:-window]
  return cumulative_arr[window - 1:] / window

arr = np.random.randint(1000, size = (10))
print(arr)
print(cumulative_mean(arr, 2))

[240 713  78 171 195 317 983 191 365 785]
[476.5 395.5 124.5 183.  256.  650.  587.  278.  575. ]


# Regular expressions


1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

In [ ]:
import re
re.search(" '(\w+)_", "'master_guid': '233880bb4c50d247f84edc9cac9e6e29_2308194320'")[1]

'233880bb4c50d247f84edc9cac9e6e29'